package com.anbaric.terra_reforged.util.init;

import com.anbaric.terra_reforged.TerraReforged;
import com.anbaric.terra_reforged.blocks.*;
import com.anbaric.terra_reforged.blocks.potionplants.*;
import com.anbaric.terra_reforged.util.Reference;
import com.anbaric.terra_reforged.util.handlers.EnumHandler.EnumBiomeType;
import net.minecraft.block.*;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraftforge.common.PlantType;
import net.minecraftforge.common.ToolType;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public final class TerraBlockRegistry
{
    public static final DeferredRegister<Block> BLOCKS = new DeferredRegister<>(ForgeRegistries.BLOCKS, Reference.MODID);

    //Soils
    public static final RegistryObject<Block> SOIL_MUD = BLOCKS.register("soil_mud", () -> new Block(Block.Properties.create(Material.EARTH).sound(SoundType.GROUND).hardnessAndResistance(0.5F, 3.0F)));
    public static final RegistryObject<Block> SOIL_ASH = BLOCKS.register("soil_ash", () -> new Block(Block.Properties.create(Material.EARTH).sound(SoundType.GROUND).hardnessAndResistance(0.5F, 3.0F)));
    public static final RegistryObject<Block> SNOW_CORRUPT = BLOCKS.register("snow_corrupt", () -> new TerraBlockSpreading(Block.Properties.create(Material.SNOW_BLOCK).sound(SoundType.SNOW).hardnessAndResistance(0.5F, 3.0F), EnumBiomeType.CORRUPT, TerraReforged.BOREAL));
    public static final RegistryObject<Block> SNOW_CRIMSON = BLOCKS.register("snow_crimson", () -> new TerraBlockSpreading(Block.Properties.create(Material.SNOW_BLOCK).sound(SoundType.SNOW).hardnessAndResistance(0.5F, 3.0F), EnumBiomeType.CRIMSON, TerraReforged.BOREAL));
    public static final RegistryObject<Block> SNOW_HALLOWED = BLOCKS.register("snow_hallowed", () -> new TerraBlockSpreading(Block.Properties.create(Material.SNOW_BLOCK).sound(SoundType.SNOW).hardnessAndResistance(0.5F, 3.0F), EnumBiomeType.HALLOWED, TerraReforged.BOREAL));
    public static final RegistryObject<Block> SNOW_CORRUPT_LAYER = BLOCKS.register("snow_corrupt_layer", () -> new TerraBlockSnowLayer(Block.Properties.create(Material.SNOW).sound(SoundType.SNOW).hardnessAndResistance(0.1F).tickRandomly()));
    public static final RegistryObject<Block> SNOW_CRIMSON_LAYER = BLOCKS.register("snow_crimson_layer", () -> new TerraBlockSnowLayer(Block.Properties.create(Material.SNOW).sound(SoundType.SNOW).hardnessAndResistance(0.1F).tickRandomly()));
    public static final RegistryObject<Block> SNOW_HALLOWED_LAYER = BLOCKS.register("snow_hallowed_layer", () -> new TerraBlockSnowLayer(Block.Properties.create(Material.SNOW).sound(SoundType.SNOW).hardnessAndResistance(0.1F).tickRandomly()));
    public static final RegistryObject<Block> GRASS_JUNGLE = BLOCKS.register("grass_jungle", () -> new TerraBlockMudGrass(Block.Properties.create(Material.ORGANIC).sound(SoundType.PLANT).hardnessAndResistance(0.5F, 3.0F).tickRandomly()));
    public static final RegistryObject<Block> GRASS_MUSHROOM = BLOCKS.register("grass_mushroom", () -> new TerraBlockMudGrass(Block.Properties.create(Material.ORGANIC).sound(SoundType.PLANT).hardnessAndResistance(0.5F, 3.0F).tickRandomly()));
    public static final RegistryObject<Block> GRASS_CORRUPT = BLOCKS.register("grass_corrupt", () -> new TerraBlockBiomeGrass(Block.Properties.create(Material.ORGANIC).sound(SoundType.WET_GRASS).hardnessAndResistance(0.5F, 3.0F).tickRandomly(), EnumBiomeType.CORRUPT));
    public static final RegistryObject<Block> GRASS_CRIMSON = BLOCKS.register("grass_crimson", () -> new TerraBlockBiomeGrass(Block.Properties.create(Material.ORGANIC).sound(SoundType.WET_GRASS).hardnessAndResistance(0.5F, 3.0F).tickRandomly(), EnumBiomeType.CRIMSON));
    public static final RegistryObject<Block> GRASS_HALLOWED = BLOCKS.register("grass_hallowed", () -> new TerraBlockBiomeGrass(Block.Properties.create(Material.ORGANIC).sound(SoundType.PLANT).hardnessAndResistance(0.5F, 3.0F).tickRandomly(), EnumBiomeType.HALLOWED));
    public static final RegistryObject<Block> SAND_EBON = BLOCKS.register("sand_ebon", () -> new TerraBlockSand(Block.Properties.create(Material.SAND).sound(SoundType.SAND).hardnessAndResistance(0.5F).tickRandomly(), EnumBiomeType.CORRUPT));
    public static final RegistryObject<Block> SAND_CRIM = BLOCKS.register("sand_crim", () -> new TerraBlockSand(Block.Properties.create(Material.SAND).sound(SoundType.SAND).hardnessAndResistance(0.5F).tickRandomly(), EnumBiomeType.CRIMSON));
    public static final RegistryObject<Block> SAND_PEARL = BLOCKS.register("sand_pearl", () -> new TerraBlockSand(Block.Properties.create(Material.SAND).sound(SoundType.SAND).hardnessAndResistance(0.5F).tickRandomly(), EnumBiomeType.HALLOWED));
    public static final RegistryObject<Block> SAND_SILT = BLOCKS.register("sand_silt", () -> new SandBlock(25, Block.Properties.create(Material.SAND).sound(SoundType.SAND).hardnessAndResistance(0.5F)));
    public static final RegistryObject<Block> SAND_SLUSH = BLOCKS.register("sand_slush", () -> new SandBlock(25, Block.Properties.create(Material.SAND).sound(SoundType.SAND).hardnessAndResistance(0.5F)));
    public static final RegistryObject<Block> SAND_HARD = BLOCKS.register("sand_hard", () -> new SandBlock(25, Block.Properties.create(Material.SAND).sound(SoundType.SAND).hardnessAndResistance(1.0F)));
    public static final RegistryObject<Block> SAND_HARDEBON = BLOCKS.register("sand_hardebon", () -> new TerraBlockSand(Block.Properties.create(Material.SAND).sound(SoundType.SAND).hardnessAndResistance(1.0F).tickRandomly(), EnumBiomeType.CORRUPT));
    public static final RegistryObject<Block> SAND_HARDCRIM = BLOCKS.register("sand_hardcrim", () -> new TerraBlockSand(Block.Properties.create(Material.SAND).sound(SoundType.SAND).hardnessAndResistance(1.0F).tickRandomly(), EnumBiomeType.CRIMSON));
    public static final RegistryObject<Block> SAND_HARDPEARL = BLOCKS.register("sand_hardpearl", () -> new TerraBlockSand(Block.Properties.create(Material.SAND).sound(SoundType.SAND).hardnessAndResistance(1.0F).tickRandomly(), EnumBiomeType.HALLOWED));

    //Stones
    public static final RegistryObject<Block> SANDSTONE_EBON = BLOCKS.register("sandstone_ebon", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).tickRandomly().hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> SANDSTONE_EBON_CHISELED = BLOCKS.register("sandstone_ebon_chiseled", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> SANDSTONE_EBON_SMOOTH = BLOCKS.register("sandstone_ebon_smooth", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> SANDSTONE_EBON_CUT = BLOCKS.register("sandstone_ebon_cut", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> SANDSTONE_CRIM = BLOCKS.register("sandstone_crim", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> SANDSTONE_CRIM_CHISELED = BLOCKS.register("sandstone_crim_chiseled", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> SANDSTONE_CRIM_SMOOTH = BLOCKS.register("sandstone_crim_smooth", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> SANDSTONE_CRIM_CUT = BLOCKS.register("sandstone_crim_cut", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> SANDSTONE_PEARL = BLOCKS.register("sandstone_pearl", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> SANDSTONE_PEARL_CHISELED = BLOCKS.register("sandstone_pearl_chiseled", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> SANDSTONE_PEARL_SMOOTH = BLOCKS.register("sandstone_pearl_smooth", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> SANDSTONE_PEARL_CUT = BLOCKS.register("sandstone_pearl_cut", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONE_EBON = BLOCKS.register("stone_ebon", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> COBBLESTONE_EBON = BLOCKS.register("cobblestone_ebon", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> COBBLESTONE_EBON_MOSSY = BLOCKS.register("cobblestone_ebon_mossy", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONEBRICK_EBON = BLOCKS.register("stonebrick_ebon", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONEBRICK_EBON_CRACKED = BLOCKS.register("stonebrick_ebon_cracked", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONEBRICK_EBON_CHISELED = BLOCKS.register("stonebrick_ebon_chiseled", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONEBRICK_EBON_MOSSY = BLOCKS.register("stonebrick_ebon_mossy", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONE_CRIM = BLOCKS.register("stone_crim", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> COBBLESTONE_CRIM = BLOCKS.register("cobblestone_crim", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> COBBLESTONE_CRIM_MOSSY = BLOCKS.register("cobblestone_crim_mossy", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONEBRICK_CRIM = BLOCKS.register("stonebrick_crim", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONEBRICK_CRIM_CRACKED = BLOCKS.register("stonebrick_crim_cracked", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONEBRICK_CRIM_CHISELED = BLOCKS.register("stonebrick_crim_chiseled", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONEBRICK_CRIM_MOSSY = BLOCKS.register("stonebrick_crim_mossy", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONE_PEARL = BLOCKS.register("stone_pearl", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> COBBLESTONE_PEARL = BLOCKS.register("cobblestone_pearl", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> COBBLESTONE_PEARL_MOSSY = BLOCKS.register("cobblestone_pearl_mossy", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONEBRICK_PEARL = BLOCKS.register("stonebrick_pearl", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONEBRICK_PEARL_CRACKED = BLOCKS.register("stonebrick_pearl_cracked", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONEBRICK_PEARL_CHISELED = BLOCKS.register("stonebrick_pearl_chiseled", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONEBRICK_PEARL_MOSSY = BLOCKS.register("stonebrick_pearl_mossy", () -> new TerraBlockSpreading(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(0.8F).tickRandomly(), EnumBiomeType.CORRUPT, PlantType.Cave));
    public static final RegistryObject<Block> STONE_MOSS_RED = BLOCKS.register("stone_moss_red", () -> new TerraBlockMoss(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).tickRandomly()));
    public static final RegistryObject<Block> STONE_MOSS_YELLOW = BLOCKS.register("stone_moss_yellow", () -> new TerraBlockMoss(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).tickRandomly()));
    public static final RegistryObject<Block> STONE_MOSS_GREEN = BLOCKS.register("stone_moss_green", () -> new TerraBlockMoss(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).tickRandomly()));
    public static final RegistryObject<Block> STONE_MOSS_BLUE = BLOCKS.register("stone_moss_blue", () -> new TerraBlockMoss(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).tickRandomly()));
    public static final RegistryObject<Block> STONE_MOSS_PURPLE = BLOCKS.register("stone_moss_purple", () -> new TerraBlockMoss(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).tickRandomly()));
    public static final RegistryObject<Block> STONE_MOSS_FIRE = BLOCKS.register("stone_moss_fire", () -> new TerraBlockMoss(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).tickRandomly()));
    public static final RegistryObject<Block> STONE_GRANITE = BLOCKS.register("stone_granite", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> STONE_MARBLE = BLOCKS.register("stone_marble", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> STONE_FOSSIL = BLOCKS.register("stone_fossil", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> ICE_PURPLE = BLOCKS.register("ice_purple", () -> new TerraBlockIce(Block.Properties.create(Material.ICE).sound(SoundType.GLASS).slipperiness(0.98F).tickRandomly().hardnessAndResistance(0.5F).notSolid(), EnumBiomeType.CORRUPT));
    public static final RegistryObject<Block> ICE_HARD_PURPLE = BLOCKS.register("ice_hard_purple", () -> new TerraBlockSpreading(Block.Properties.create(Material.PACKED_ICE).sound(SoundType.GLASS).hardnessAndResistance(0.8F), EnumBiomeType.CORRUPT, TerraReforged.BOREAL));
    public static final RegistryObject<Block> ICE_RED = BLOCKS.register("ice_red", () -> new TerraBlockIce(Block.Properties.create(Material.ICE).sound(SoundType.GLASS).slipperiness(0.98F).tickRandomly().hardnessAndResistance(0.5F).notSolid(), EnumBiomeType.CRIMSON));
    public static final RegistryObject<Block> ICE_HARD_RED = BLOCKS.register("ice_hard_red", () -> new TerraBlockSpreading(Block.Properties.create(Material.PACKED_ICE).sound(SoundType.GLASS).hardnessAndResistance(0.8F), EnumBiomeType.CRIMSON, TerraReforged.BOREAL));
    public static final RegistryObject<Block> ICE_PINK = BLOCKS.register("ice_pink", () -> new TerraBlockIce(Block.Properties.create(Material.ICE).sound(SoundType.GLASS).slipperiness(0.98F).tickRandomly().hardnessAndResistance(0.5F).notSolid(), EnumBiomeType.HALLOWED));
    public static final RegistryObject<Block> ICE_HARD_PINK = BLOCKS.register("ice_hard_pink", () -> new TerraBlockSpreading(Block.Properties.create(Material.PACKED_ICE).sound(SoundType.GLASS).hardnessAndResistance(0.8F), EnumBiomeType.HALLOWED, TerraReforged.BOREAL));
    public static final RegistryObject<Block> ICE_THIN = BLOCKS.register("ice_thin", () -> new TerraBlockThinIce(Block.Properties.create(Material.ICE).sound(SoundType.GLASS).slipperiness(0.98F).hardnessAndResistance(0.25F).notSolid()));

    //Woods
    public static final RegistryObject<Block> LOG_BOREAL = BLOCKS.register("log_boreal", () -> new LogBlock(MaterialColor.BROWN_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_PALM = BLOCKS.register("log_palm", () -> new LogBlock(MaterialColor.YELLOW_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_MAHOGANY = BLOCKS.register("log_mahogany", () -> new LogBlock(MaterialColor.NETHERRACK, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_EBON = BLOCKS.register("log_ebon", () -> new LogBlock(MaterialColor.PURPLE_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_SHADE = BLOCKS.register("log_shade", () -> new LogBlock(MaterialColor.RED_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_PEARL = BLOCKS.register("log_pearl", () -> new LogBlock(MaterialColor.PINK_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_BOREAL_SOLID = BLOCKS.register("log_boreal_solid", () -> new LogBlock(MaterialColor.BROWN_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_PALM_SOLID = BLOCKS.register("log_palm_solid", () -> new LogBlock(MaterialColor.YELLOW_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_MAHOGANY_SOLID = BLOCKS.register("log_mahogany_solid", () -> new LogBlock(MaterialColor.NETHERRACK, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_EBON_SOLID = BLOCKS.register("log_ebon_solid", () -> new LogBlock(MaterialColor.PURPLE_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_SHADE_SOLID = BLOCKS.register("log_shade_solid", () -> new LogBlock(MaterialColor.RED_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_PEARL_SOLID = BLOCKS.register("log_pearl_solid", () -> new LogBlock(MaterialColor.PINK_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_BOREAL_STRIPPED = BLOCKS.register("log_boreal_stripped", () -> new LogBlock(MaterialColor.BROWN_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_PALM_STRIPPED = BLOCKS.register("log_palm_stripped", () -> new LogBlock(MaterialColor.YELLOW_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_MAHOGANY_STRIPPED = BLOCKS.register("log_mahogany_stripped", () -> new LogBlock(MaterialColor.NETHERRACK, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_EBON_STRIPPED = BLOCKS.register("log_ebon_stripped", () -> new LogBlock(MaterialColor.PURPLE_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_SHADE_STRIPPED = BLOCKS.register("log_shade_stripped", () -> new LogBlock(MaterialColor.RED_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_PEARL_STRIPPED = BLOCKS.register("log_pearl_stripped", () -> new LogBlock(MaterialColor.PINK_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_BOREAL_SOLID_STRIPPED = BLOCKS.register("log_boreal_solid_stripped", () -> new LogBlock(MaterialColor.BROWN_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_PALM_SOLID_STRIPPED = BLOCKS.register("log_palm_solid_stripped", () -> new LogBlock(MaterialColor.YELLOW_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_MAHOGANY_SOLID_STRIPPED = BLOCKS.register("log_mahogany_solid_stripped", () -> new LogBlock(MaterialColor.NETHERRACK, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_EBON_SOLID_STRIPPED = BLOCKS.register("log_ebon_solid_stripped", () -> new LogBlock(MaterialColor.PURPLE_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_SHADE_SOLID_STRIPPED = BLOCKS.register("log_shade_solid_stripped", () -> new LogBlock(MaterialColor.RED_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_PEARL_SOLID_STRIPPED = BLOCKS.register("log_pearl_solid_stripped", () -> new LogBlock(MaterialColor.PINK_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> LOG_MUSHROOM = BLOCKS.register("log_mushroom", () -> new LogBlock(MaterialColor.CYAN_TERRACOTTA, Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F)));
    public static final RegistryObject<Block> MUSHROOM_CAP = BLOCKS.register("mushroom_cap", () -> new HugeMushroomBlock(Block.Properties.create(Material.WOOD, MaterialColor.BLUE).hardnessAndResistance(0.2F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PLANK_BOREAL = BLOCKS.register("plank_boreal", () -> new Block(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.2F, 0.3F)));
    public static final RegistryObject<Block> PLANK_PALM = BLOCKS.register("plank_palm", () -> new Block(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.2F, 0.3F)));
    public static final RegistryObject<Block> PLANK_MAHOGANY = BLOCKS.register("plank_mahogany", () -> new Block(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.2F, 0.3F)));
    public static final RegistryObject<Block> PLANK_EBON = BLOCKS.register("plank_ebon", () -> new Block(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.2F, 0.3F)));
    public static final RegistryObject<Block> PLANK_SHADE = BLOCKS.register("plank_shade", () -> new Block(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.2F, 0.3F)));
    public static final RegistryObject<Block> PLANK_PEARL = BLOCKS.register("plank_pearl", () -> new Block(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.2F, 0.3F)));
    public static final RegistryObject<Block> PLANK_SPOOKY = BLOCKS.register("plank_spooky", () -> new Block(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.2F, 0.3F)));
    public static final RegistryObject<Block> PLANK_DYNASTY = BLOCKS.register("plank_dynasty", () -> new Block(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.2F, 0.3F)));

    //Foliage
    public static final RegistryObject<Block> PLANT_MOSS_RED = BLOCKS.register("plant_moss_red", () -> new TerraBlockFoliage(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_MOSS_YELLOW = BLOCKS.register("plant_moss_yellow", () -> new TerraBlockFoliage(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_MOSS_GREEN = BLOCKS.register("plant_moss_green", () -> new TerraBlockFoliage(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_MOSS_BLUE = BLOCKS.register("plant_moss_blue", () -> new TerraBlockFoliage(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_MOSS_PURPLE = BLOCKS.register("plant_moss_purple", () -> new TerraBlockFoliage(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_MOSS_FIRE = BLOCKS.register("plant_moss_fire", () -> new TerraBlockFoliage(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_BLINKROOT = BLOCKS.register("plant_blinkroot", () -> new TerraBlockBlinkroot(Block.Properties.create(Material.PLANTS).sound(SoundType.CROP).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_DAYBLOOM = BLOCKS.register("plant_daybloom", () -> new TerraBlockDaybloom(Block.Properties.create(Material.PLANTS).sound(SoundType.CROP).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_DEATHWEED = BLOCKS.register("plant_deathweed", () -> new TerraBlockDeathweed(Block.Properties.create(Material.PLANTS).sound(SoundType.CROP).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_FIREBLOSSOM = BLOCKS.register("plant_fireblossom", () -> new TerraBlockFireblossom(Block.Properties.create(Material.PLANTS).sound(SoundType.CROP).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_MOONGLOW = BLOCKS.register("plant_moonglow", () -> new TerraBlockMoonglow(Block.Properties.create(Material.PLANTS).sound(SoundType.CROP).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_SHIVERTHORN = BLOCKS.register("plant_shiverthorn", () -> new TerraBlockShiverthorn(Block.Properties.create(Material.PLANTS).sound(SoundType.CROP).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_WATERLEAF = BLOCKS.register("plant_waterleaf", () -> new TerraBlockWaterleaf(Block.Properties.create(Material.PLANTS).sound(SoundType.CROP).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_MUSHROOM_GLOWING = BLOCKS.register("plant_mushroom_glowing", () -> new TerraBlockFoliage(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_MUSHROOM_VILE = BLOCKS.register("plant_mushroom_vile", () -> new TerraBlockFoliage(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_MUSHROOM_VICIOUS = BLOCKS.register("plant_mushroom_vicious", () -> new TerraBlockFoliage(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_LIFEFRUIT = BLOCKS.register("plant_lifefruit", () -> new TerraBlockFoliage(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_BLOODROOT = BLOCKS.register("plant_bloodroot", () -> new TerraBlockHangingPlant(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> PLANT_DYE_PURPLE = BLOCKS.register("plant_dye_purple", () -> new DoublePlantBlock(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.5F)));
    public static final RegistryObject<Block> PLANT_DYE_ORANGE = BLOCKS.register("plant_dye_orange", () -> new DoublePlantBlock(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.5F)));
    public static final RegistryObject<Block> PLANT_DYE_CYAN = BLOCKS.register("plant_dye_cyan", () -> new DoublePlantBlock(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.5F)));
    public static final RegistryObject<Block> PLANT_DYE_RED = BLOCKS.register("plant_dye_red", () -> new DoublePlantBlock(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().hardnessAndResistance(0.5F)));
    /*public static final RegistryObject<Block> PLANT_BULB = null;*/
    public static final RegistryObject<Block> PLANT_THORN_PURPLE = BLOCKS.register("plant_thorn_purple", () -> new TerraBlockThornBush(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).tickRandomly(), 4.0F));
    public static final RegistryObject<Block> PLANT_THORN_RED = BLOCKS.register("plant_thorn_red", () -> new TerraBlockThornBush(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).tickRandomly(), 4.0F));
    public static final RegistryObject<Block> PLANT_THORN_JUNGLE = BLOCKS.register("plant_thorn_jungle", () -> new TerraBlockThornBush(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).tickRandomly(), 8.0F));
    public static final RegistryObject<Block> LEAF_BOREAL = BLOCKS.register("leaf_boreal", () -> new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()));
    public static final RegistryObject<Block> LEAF_PALM = BLOCKS.register("leaf_palm", () -> new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()));
    public static final RegistryObject<Block> LEAF_MAHOGANY = BLOCKS.register("leaf_mahogany", () -> new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()));
    public static final RegistryObject<Block> LEAF_EBON = BLOCKS.register("leaf_ebon", () -> new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()));
    public static final RegistryObject<Block> LEAF_SHADE = BLOCKS.register("leaf_shade", () -> new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()));
    public static final RegistryObject<Block> LEAF_PEARL_RED = BLOCKS.register("leaf_pearl_red", () -> new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()));
    public static final RegistryObject<Block> LEAF_PEARL_YELLOW = BLOCKS.register("leaf_pearl_yellow", () -> new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()));
    public static final RegistryObject<Block> LEAF_PEARL_PINK = BLOCKS.register("leaf_pearl_pink", () -> new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()));
    public static final RegistryObject<Block> LEAF_PEARL_MAGENTA = BLOCKS.register("leaf_pearl_magenta", () -> new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()));
    public static final RegistryObject<Block> LEAF_PEARL_CYAN = BLOCKS.register("leaf_pearl_cyan", () -> new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()));
    public static final RegistryObject<Block> LEAF_PEARL_BLUE = BLOCKS.register("leaf_pearl_blue", () -> new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()));
    public static final RegistryObject<Block> LEAF_PEARL_GREEN = BLOCKS.register("leaf_pearl_green", () -> new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()));
    public static final RegistryObject<Block> LEAF_PEARL_PURPLE = BLOCKS.register("leaf_pearl_purple", () -> new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()));
//    public static final RegistryObject<Block> SAPLING_BOREAL = null;
//    public static final RegistryObject<Block> SAPLING_PALM = null;
//    public static final RegistryObject<Block> SAPLING_MAHOGANY = null;
//    public static final RegistryObject<Block> SAPLING_EBON = null;
//    public static final RegistryObject<Block> SAPLING_SHADE = null;
//    public static final RegistryObject<Block> SAPLING_PEARL = null;
    public static final RegistryObject<Block> CACTUS_EBON = BLOCKS.register("cactus_ebon", () -> new TerraBlockCactus(Block.Properties.create(Material.CACTUS).tickRandomly().hardnessAndResistance(0.4F).sound(SoundType.CLOTH)));
    public static final RegistryObject<Block> CACTUS_CRIM = BLOCKS.register("cactus_crim", () -> new TerraBlockCactus(Block.Properties.create(Material.CACTUS).tickRandomly().hardnessAndResistance(0.4F).sound(SoundType.CLOTH)));
    public static final RegistryObject<Block> CACTUS_PEARL = BLOCKS.register("cactus_pearl", () -> new TerraBlockCactus(Block.Properties.create(Material.CACTUS).tickRandomly().hardnessAndResistance(0.4F).sound(SoundType.CLOTH)));
    public static final RegistryObject<Block> REED_CORRUPT = BLOCKS.register("reed_corrupt", () -> new TerraBlockReeds(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> REED_CRIMSON = BLOCKS.register("reed_crimson", () -> new TerraBlockReeds(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> REED_HALLOWED = BLOCKS.register("reed_hallowed", () -> new TerraBlockReeds(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0.0F)));
    public static final RegistryObject<Block> TALLGRASS_CORRUPT = BLOCKS.register("tallgrass_corrupt", () -> new TerraBlockTallGrass(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).hardnessAndResistance(0.0F).doesNotBlockMovement().notSolid()));
    public static final RegistryObject<Block> TALLGRASS_CRIMSON = BLOCKS.register("tallgrass_crimson", () -> new TerraBlockTallGrass(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).hardnessAndResistance(0.0F).doesNotBlockMovement().notSolid()));
    public static final RegistryObject<Block> TALLGRASS_HALLOWED = BLOCKS.register("tallgrass_hallowed", () -> new TerraBlockTallGrass(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).hardnessAndResistance(0.0F).doesNotBlockMovement().notSolid()));
    public static final RegistryObject<Block> TALLGRASSDOUBLE_CORRUPT = BLOCKS.register("tallgrassdouble_corrupt", () -> new DoublePlantBlock(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).hardnessAndResistance(0.0F).doesNotBlockMovement().notSolid()));
    public static final RegistryObject<Block> TALLGRASSDOUBLE_CRIMSON = BLOCKS.register("tallgrassdouble_crimson", () -> new DoublePlantBlock(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).hardnessAndResistance(0.0F).doesNotBlockMovement().notSolid()));
    public static final RegistryObject<Block> TALLGRASSDOUBLE_HALLOWED = BLOCKS.register("tallgrassdouble_hallowed", () -> new DoublePlantBlock(Block.Properties.create(Material.PLANTS).sound(SoundType.PLANT).hardnessAndResistance(0.0F).doesNotBlockMovement().notSolid()));

    //Structure Misc
    public static final RegistryObject<Block> WALL_OAK = BLOCKS.register("wall_oak", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_SPRUCE = BLOCKS.register("wall_spruce", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_BIRCH = BLOCKS.register("wall_birch", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_JUNGLE = BLOCKS.register("wall_jungle", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_ACACIA = BLOCKS.register("wall_acacia", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_DARKOAK = BLOCKS.register("wall_darkoak", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_OAK_LEAF = BLOCKS.register("wall_oak_leaf", () -> new TerraBlockWall(Block.Properties.create(Material.LEAVES).sound(SoundType.PLANT).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_SPRUCE_LEAF = BLOCKS.register("wall_spruce_leaf", () -> new TerraBlockWall(Block.Properties.create(Material.LEAVES).sound(SoundType.PLANT).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_BIRCH_LEAF = BLOCKS.register("wall_birch_leaf", () -> new TerraBlockWall(Block.Properties.create(Material.LEAVES).sound(SoundType.PLANT).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_JUNGLE_LEAF = BLOCKS.register("wall_jungle_leaf", () -> new TerraBlockWall(Block.Properties.create(Material.LEAVES).sound(SoundType.PLANT).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_ACACIA_LEAF = BLOCKS.register("wall_acacia_leaf", () -> new TerraBlockWall(Block.Properties.create(Material.LEAVES).sound(SoundType.PLANT).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_DARKOAK_LEAF = BLOCKS.register("wall_darkoak_leaf", () -> new TerraBlockWall(Block.Properties.create(Material.LEAVES).sound(SoundType.PLANT).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_BOREAL = BLOCKS.register("wall_boreal", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_PALM = BLOCKS.register("wall_palm", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_MAHOGANY = BLOCKS.register("wall_mahogany", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_EBON = BLOCKS.register("wall_ebon", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_SHADE = BLOCKS.register("wall_shade", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_PEARL = BLOCKS.register("wall_pearl", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_BOREAL_LEAF = BLOCKS.register("wall_boreal_leaf", () -> new TerraBlockWall(Block.Properties.create(Material.LEAVES).sound(SoundType.PLANT).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_PALM_LEAF = BLOCKS.register("wall_palm_leaf", () -> new TerraBlockWall(Block.Properties.create(Material.LEAVES).sound(SoundType.PLANT).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_MAHOGANY_LEAF = BLOCKS.register("wall_mahogany_leaf", () -> new TerraBlockWall(Block.Properties.create(Material.LEAVES).sound(SoundType.PLANT).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_EBON_LEAF = BLOCKS.register("wall_ebon_leaf", () -> new TerraBlockWall(Block.Properties.create(Material.LEAVES).sound(SoundType.PLANT).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_SHADE_LEAF = BLOCKS.register("wall_shade_leaf", () -> new TerraBlockWall(Block.Properties.create(Material.LEAVES).sound(SoundType.PLANT).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_PEARL_LEAF = BLOCKS.register("wall_pearl_leaf", () -> new TerraBlockWall(Block.Properties.create(Material.LEAVES).sound(SoundType.PLANT).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_OAK_PLANK = BLOCKS.register("wall_oak_plank", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_SPRUCE_PLANK = BLOCKS.register("wall_spruce_plank", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));;
    public static final RegistryObject<Block> WALL_BIRCH_PLANK = BLOCKS.register("wall_birch_plank", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_JUNGLE_PLANK = BLOCKS.register("wall_jungle_plank", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_ACACIA_PLANK = BLOCKS.register("wall_acacia_plank", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_DARKOAK_PLANK = BLOCKS.register("wall_dark_oak_plank", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_BOREAL_PLANK = BLOCKS.register("wall_boreal_plank", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_PALM_PLANK = BLOCKS.register("wall_palm_plank", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_MAHOGANY_PLANK = BLOCKS.register("wall_mahogany_plank", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_EBON_PLANK = BLOCKS.register("wall_ebon_plank", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_SHADE_PLANK = BLOCKS.register("wall_shade_plank", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_PEARL_PLANK = BLOCKS.register("wall_pearl_plank", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_DYNASTY_PLANK = BLOCKS.register("wall_dynasty_plank", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_SPOOKY_PLANK = BLOCKS.register("wall_spooky_plank", () -> new TerraBlockWall(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 6.0F)));
    public static final RegistryObject<Block> WALL_STONEBRICK_EBON = BLOCKS.register("wall_stonebrick_ebon", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(2.0F, 6.0F)));
    public static final RegistryObject<Block> WALL_STONEBRICK_CRIM = BLOCKS.register("wall_stonebrick_crim", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(2.0F, 6.0F)));
    public static final RegistryObject<Block> WALL_STONEBRICK_PEARL = BLOCKS.register("wall_stonebrick_pearl", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(2.0F, 6.0F)));
    public static final RegistryObject<Block> WALL_COBBLESTONE_EBON = BLOCKS.register("wall_cobblestone_ebon", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(2.0F, 6.0F)));
    public static final RegistryObject<Block> WALL_COBBLESTONE_CRIM = BLOCKS.register("wall_cobblestone_crim", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(2.0F, 6.0F)));
    public static final RegistryObject<Block> WALL_COBBLESTONE_PEARL = BLOCKS.register("wall_cobblestone_pearl", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(2.0F, 6.0F)));
    public static final RegistryObject<Block> WALL_SANDSTONE_EBON = BLOCKS.register("wall_sandstone_ebon", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(2.0F, 6.0F)));
    public static final RegistryObject<Block> WALL_SANDSTONE_CRIM = BLOCKS.register("wall_sandstone_crim", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(2.0F, 6.0F)));
    public static final RegistryObject<Block> WALL_SANDSTONE_PEARL = BLOCKS.register("wall_sandstone_pearl", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(2.0F, 6.0F)));

    public static final RegistryObject<Block> STAIR_BOREAL = BLOCKS.register("stair_boreal", () -> new StairsBlock(() -> TerraBlockRegistry.PLANK_BOREAL.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.PLANK_BOREAL.get())));
    public static final RegistryObject<Block> STAIR_PALM = BLOCKS.register("stair_palm", () -> new StairsBlock(() -> TerraBlockRegistry.PLANK_PALM.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.PLANK_PALM.get())));
    public static final RegistryObject<Block> STAIR_MAHOGANY = BLOCKS.register("stair_mahogany", () -> new StairsBlock(() -> TerraBlockRegistry.PLANK_MAHOGANY.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.PLANK_MAHOGANY.get())));
    public static final RegistryObject<Block> STAIR_EBON = BLOCKS.register("stair_ebon", () -> new StairsBlock(() -> TerraBlockRegistry.PLANK_EBON.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.PLANK_EBON.get())));
    public static final RegistryObject<Block> STAIR_SHADE = BLOCKS.register("stair_shade", () -> new StairsBlock(() -> TerraBlockRegistry.PLANK_SHADE.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.PLANK_SHADE.get())));
    public static final RegistryObject<Block> STAIR_PEARL = BLOCKS.register("stair_pearl", () -> new StairsBlock(() -> TerraBlockRegistry.PLANK_PEARL.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.PLANK_PEARL.get())));

    //Structure Dungeon
    public static final RegistryObject<Block> DUNGEON_BLUE_FLOOR_BRICK = BLOCKS.register("dungeon_blue_floor_brick", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_BLUE_FLOOR_TILE = BLOCKS.register("dungeon_blue_floor_tile", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_BLUE_FLOOR_SLAB = BLOCKS.register("dungeon_blue_floor_slab", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_BLUE_WALL_BASE = BLOCKS.register("dungeon_blue_wall_base", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_BLUE_WALL_TOP = BLOCKS.register("dungeon_blue_wall_top", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_BLUE_WALL_MID = BLOCKS.register("dungeon_blue_wall_mid", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_BLUE_WALL_BOT = BLOCKS.register("dungeon_blue_wall_bot", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_BLUE_PILLAR = BLOCKS.register("dungeon_blue_pillar", () -> new RotatedPillarBlock(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_BLUE_BRICK = BLOCKS.register("dungeon_blue_brick", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_BLUE_SLAB = BLOCKS.register("dungeon_blue_slab", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> WALL_DUNGEON_BLUE_BRICKS = BLOCKS.register("wall_dungeon_blue_bricks", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> WALL_DUNGEON_BLUE_BRICK = BLOCKS.register("wall_dungeon_blue_brick", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> WALL_DUNGEON_BLUE_TILE = BLOCKS.register("wall_dungeon_blue_tile", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> WALL_DUNGEON_BLUE_SLAB = BLOCKS.register("wall_dungeon_blue_slab", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> WALL_DUNGEON_BLUE_WALL = BLOCKS.register("wall_dungeon_blue_wall", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> STAIR_DUNGEON_BLUE_BRICKS = BLOCKS.register("stair_dungeon_blue_bricks", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_BLUE_BRICK.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_BLUE_BRICK.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_BLUE_BRICK = BLOCKS.register("stair_dungeon_blue_brick", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_BLUE_FLOOR_BRICK.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_BLUE_FLOOR_BRICK.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_BLUE_TILE = BLOCKS.register("stair_dungeon_blue_tile", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_BLUE_FLOOR_TILE.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_BLUE_FLOOR_TILE.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_BLUE_SLAB = BLOCKS.register("stair_dungeon_blue_slab", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_BLUE_FLOOR_SLAB.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_BLUE_FLOOR_SLAB.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_BLUE_TRIM_TOP = BLOCKS.register("stair_dungeon_blue_trim_top", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_BLUE_WALL_TOP.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_BLUE_WALL_TOP.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_BLUE_TRIM_MID = BLOCKS.register("stair_dungeon_blue_trim_mid", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_BLUE_WALL_MID.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_BLUE_WALL_MID.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_BLUE_TRIM_BOT = BLOCKS.register("stair_dungeon_blue_trim_bot", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_BLUE_WALL_BOT.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_BLUE_WALL_BOT.get())));

    public static final RegistryObject<Block> DUNGEON_GREEN_FLOOR_BRICK = BLOCKS.register("dungeon_green_floor_brick", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_GREEN_FLOOR_TILE = BLOCKS.register("dungeon_green_floor_tile", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_GREEN_FLOOR_SLAB = BLOCKS.register("dungeon_green_floor_slab", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_GREEN_WALL_BASE = BLOCKS.register("dungeon_green_wall_base", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_GREEN_WALL_TOP = BLOCKS.register("dungeon_green_wall_top", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_GREEN_WALL_MID = BLOCKS.register("dungeon_green_wall_mid", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_GREEN_WALL_BOT = BLOCKS.register("dungeon_green_wall_bot", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_GREEN_PILLAR = BLOCKS.register("dungeon_green_pillar", () -> new RotatedPillarBlock(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_GREEN_BRICK = BLOCKS.register("dungeon_green_brick", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_GREEN_SLAB = BLOCKS.register("dungeon_green_slab", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> WALL_DUNGEON_GREEN_BRICKS = BLOCKS.register("wall_dungeon_green_bricks", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> WALL_DUNGEON_GREEN_BRICK = BLOCKS.register("wall_dungeon_green_brick", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> WALL_DUNGEON_GREEN_TILE = BLOCKS.register("wall_dungeon_green_tile", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> WALL_DUNGEON_GREEN_SLAB = BLOCKS.register("wall_dungeon_green_slab", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> WALL_DUNGEON_GREEN_WALL = BLOCKS.register("wall_dungeon_green_wall", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> STAIR_DUNGEON_GREEN_BRICKS = BLOCKS.register("stair_dungeon_green_bricks", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_GREEN_BRICK.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_GREEN_BRICK.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_GREEN_BRICK = BLOCKS.register("stair_dungeon_green_brick", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_GREEN_FLOOR_BRICK.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_GREEN_FLOOR_BRICK.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_GREEN_TILE = BLOCKS.register("stair_dungeon_green_tile", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_GREEN_FLOOR_TILE.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_GREEN_FLOOR_TILE.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_GREEN_SLAB = BLOCKS.register("stair_dungeon_green_slab", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_GREEN_FLOOR_SLAB.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_GREEN_FLOOR_SLAB.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_GREEN_TRIM_TOP = BLOCKS.register("stair_dungeon_green_trim_top", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_GREEN_WALL_TOP.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_GREEN_WALL_TOP.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_GREEN_TRIM_MID = BLOCKS.register("stair_dungeon_green_trim_mid", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_GREEN_WALL_MID.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_GREEN_WALL_MID.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_GREEN_TRIM_BOT = BLOCKS.register("stair_dungeon_green_trim_bot", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_GREEN_WALL_BOT.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_GREEN_WALL_BOT.get())));
//
    public static final RegistryObject<Block> DUNGEON_RED_FLOOR_BRICK = BLOCKS.register("dungeon_red_floor_brick", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_RED_FLOOR_TILE = BLOCKS.register("dungeon_red_floor_tile", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_RED_FLOOR_SLAB = BLOCKS.register("dungeon_red_floor_slab", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_RED_WALL_BASE = BLOCKS.register("dungeon_red_wall_base", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_RED_WALL_TOP = BLOCKS.register("dungeon_red_wall_top", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_RED_WALL_MID = BLOCKS.register("dungeon_red_wall_mid", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_RED_WALL_BOT = BLOCKS.register("dungeon_red_wall_bot", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_RED_PILLAR = BLOCKS.register("dungeon_red_pillar", () -> new RotatedPillarBlock(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_RED_BRICK = BLOCKS.register("dungeon_red_brick", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> DUNGEON_RED_SLAB = BLOCKS.register("dungeon_red_slab", () -> new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F).harvestLevel(3).harvestTool(ToolType.PICKAXE)));
    public static final RegistryObject<Block> WALL_DUNGEON_RED_BRICKS = BLOCKS.register("wall_dungeon_red_bricks", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> WALL_DUNGEON_RED_BRICK = BLOCKS.register("wall_dungeon_red_brick", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> WALL_DUNGEON_RED_TILE = BLOCKS.register("wall_dungeon_red_tile", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> WALL_DUNGEON_RED_SLAB = BLOCKS.register("wall_dungeon_red_slab", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> WALL_DUNGEON_RED_WALL = BLOCKS.register("wall_dungeon_red_wall", () -> new TerraBlockWall(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(9.0F, 9.0F)));
    public static final RegistryObject<Block> STAIR_DUNGEON_RED_BRICKS = BLOCKS.register("stair_dungeon_red_bricks", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_RED_BRICK.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_RED_BRICK.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_RED_BRICK = BLOCKS.register("stair_dungeon_red_brick", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_RED_FLOOR_BRICK.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_RED_FLOOR_BRICK.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_RED_TILE = BLOCKS.register("stair_dungeon_red_tile", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_RED_FLOOR_TILE.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_RED_FLOOR_TILE.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_RED_SLAB = BLOCKS.register("stair_dungeon_red_slab", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_RED_FLOOR_SLAB.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_RED_FLOOR_SLAB.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_RED_TRIM_TOP = BLOCKS.register("stair_dungeon_red_trim_top", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_RED_WALL_TOP.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_RED_WALL_TOP.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_RED_TRIM_MID = BLOCKS.register("stair_dungeon_red_trim_mid", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_RED_WALL_MID.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_RED_WALL_MID.get())));
    public static final RegistryObject<Block> STAIR_DUNGEON_RED_TRIM_BOT = BLOCKS.register("stair_dungeon_red_trim_bot", () -> new StairsBlock(() -> TerraBlockRegistry.DUNGEON_RED_WALL_BOT.get().getDefaultState(), Block.Properties.from(TerraBlockRegistry.DUNGEON_RED_WALL_BOT.get())));
//
//    //Structure Temple
//    public static final RegistryObject<Block> LIHZAHRD_BRICK = null;
//
//    //Bricks
//    public static final RegistryObject<Block> BRICK_SNOW = null;
//    public static final RegistryObject<Block> BRICK_ICE = null;
//    public static final RegistryObject<Block> BRICK_MUDSTONE = null;
//    public static final RegistryObject<Block> BRICK_ASHSTONE = null;
//    public static final RegistryObject<Block> BRICK_EBONSTONE = null;
//    public static final RegistryObject<Block> BRICK_PEARLSTONE = null;
//    public static final RegistryObject<Block> BRICK_COPPER = null;
//    public static final RegistryObject<Block> BRICK_TIN = null;
//    public static final RegistryObject<Block> BRICK_SILVER = null;
//    public static final RegistryObject<Block> BRICK_TUNGSTEN = null;
//    public static final RegistryObject<Block> BRICK_GOLD = null;
//    public static final RegistryObject<Block> BRICK_PLATINUM = null;
//    public static final RegistryObject<Block> BRICK_DEMONITE = null;
//    public static final RegistryObject<Block> BRICK_CRIMTANE = null;
//    public static final RegistryObject<Block> BRICK_METEORITE = null;
//    public static final RegistryObject<Block> BRICK_OBSIDIAN = null;
//    public static final RegistryObject<Block> BRICK_HELLSTONE = null;
//    public static final RegistryObject<Block> BRICK_COBALT = null;
//    public static final RegistryObject<Block> BRICK_PALLADIUM = null;
//    public static final RegistryObject<Block> BRICK_MYTHRIL = null;
//    public static final RegistryObject<Block> BRICK_ORICHALCUM = null;
//    public static final RegistryObject<Block> BRICK_ADAMANTITE = null;
//    public static final RegistryObject<Block> BRICK_TITANIUM = null;
//    public static final RegistryObject<Block> BRICK_CHLOROPHYTE = null;
//    public static final RegistryObject<Block> BRICK_LUMINITE = null;
//    public static final RegistryObject<Block> BRICK_RAINBOW = null;
//    public static final RegistryObject<Block> BRICK_SUNPLATE = null;
//    public static final RegistryObject<Block> BRICK_STUCCO = null;
//    public static final RegistryObject<Block> BRICK_STUCCO_RED = null;
//    public static final RegistryObject<Block> BRICK_STUCCO_GREEN = null;
//    public static final RegistryObject<Block> BRICK_STUCCO_YELLOW = null;
//    public static final RegistryObject<Block> BRICK_FLESH = null;
//    public static final RegistryObject<Block> BRICK_STONE = null;
//    public static final RegistryObject<Block> BRICK_SANDSTONE = null;
//    public static final RegistryObject<Block> PLATE_TIN = null;
//    public static final RegistryObject<Block> PLATE_COPPER = null;
//    public static final RegistryObject<Block> PLATE_MARTIAN = null;
//    public static final RegistryObject<Block> PLATE_SHROOMITE = null;
//    public static final RegistryObject<Block> BRICK_CRYSTAL = null;
//    public static final RegistryObject<Block> BRICK_GRANITE = null;
//    public static final RegistryObject<Block> BRICK_MARBLE = null;
//
//    //Ores
//    public static final RegistryObject<Block> ORE_COPPER = BLOCKS.register("ore_copper", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_TIN = BLOCKS.register("ore_tin", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_LEAD = BLOCKS.register("ore_lead", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_IRON = BLOCKS.register("ore_iron", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_SILVER = BLOCKS.register("ore_silver", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_TUNGSTEN = BLOCKS.register("ore_tungsten", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_GOLD = BLOCKS.register("ore_gold", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_PLATINUM = BLOCKS.register("ore_platinum", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_METEORITE = BLOCKS.register("ore_meteorite", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_DEMONITE = BLOCKS.register("ore_demonite", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_CRIMTANE = BLOCKS.register("ore_crimtane", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_HELLSTONE = BLOCKS.register("ore_hellstone", () -> new TerraBlockOre(Block.Properties.create(Material.EARTH).sound(SoundType.GROUND).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_COBALT = BLOCKS.register("ore_cobalt", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_PALLADIUM = BLOCKS.register("ore_palladium", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_MYTHRIL = BLOCKS.register("ore_mythril", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_ORICHALCUM = BLOCKS.register("ore_orichalcum", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_ADAMANTITE = BLOCKS.register("ore_adamantite", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_TITANIUM = BLOCKS.register("ore_titanium", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_CHLOROPHYTE = BLOCKS.register("ore_chlorophyte", () -> new TerraBlockOre(Block.Properties.create(Material.EARTH).sound(SoundType.GROUND).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_COAL = BLOCKS.register("ore_coal", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_LAPIS = BLOCKS.register("ore_lapis", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_REDSTONE = BLOCKS.register("ore_redstone", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_AMETHYST = BLOCKS.register("ore_amethyst", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_TOPAZ = BLOCKS.register("ore_topaz", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_SAPPHIRE = BLOCKS.register("ore_sapphire", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_RUBY = BLOCKS.register("ore_ruby", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_EMERALD = BLOCKS.register("ore_emerald", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//    public static final RegistryObject<Block> ORE_DIAMOND = BLOCKS.register("ore_diamond", () -> new TerraBlockOre(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F)));
//
//    //Misc
//    public static final RegistryObject<Block> MISC_CLOUD = null;
//    public static final RegistryObject<Block> MISC_RAINCLOUD = null;
//    public static final RegistryObject<Block> MISC_HIVE = null;
//    public static final RegistryObject<Block> MISC_HONEY = null;
//    public static final RegistryObject<Block> MISC_CRISPYHONEY = null;
//    public static final RegistryObject<Block> SLIME_ALT = null;
//    public static final RegistryObject<Block> SLIME_FROZEN = null;
//    public static final RegistryObject<Block> SLIME_BOUNCY = null;
//    public static final RegistryObject<Block> MISC_ASPHALT = null;
//    public static final RegistryObject<Block> MISC_SHINGLE_BLUE = null;
//    public static final RegistryObject<Block> MISC_SHINGLE_RED = null;
//    public static final RegistryObject<Block> MISC_COG = null;
//    public static final RegistryObject<Block> MISC_CANDY_RED = null;
//    public static final RegistryObject<Block> MISC_CANDY_GREEN = null;
//    public static final RegistryObject<Block> MISC_BONE = null;
//    public static final RegistryObject<Block> MISC_ROPE = null;
//    public static final RegistryObject<Block> MISC_ROPE_VINE = null;
//    public static final RegistryObject<Block> MISC_ROPE_WEB = null;
//    public static final RegistryObject<Block> MISC_ROPE_SILK = null;
//    public static final RegistryObject<Block> MISC_CHAIN = null;
//
//    //Traps
//    public static final RegistryObject<Block> TRAP_DART = null;
//    public static final RegistryObject<Block> TRAP_SUPERDART = null;
//    public static final RegistryObject<Block> TRAP_BALL = null;
//    public static final RegistryObject<Block> TRAP_SPEAR = null;
//    public static final RegistryObject<Block> TRAP_FLAME = null;
//    public static final RegistryObject<Block> TRAP_SPIKE = null;
//    public static final RegistryObject<Block> TRAP_SUPERSPIKE = null;
//    public static final RegistryObject<Block> TRAP_GEYSER = null;
}
